version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: love-diary-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: love_diary
      MYSQL_USER: love_diary
      MYSQL_PASSWORD: love_diary123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: ./backend
    container_name: love-diary-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/love_diary?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: love_diary
      SPRING_DATASOURCE_PASSWORD: love_diary123
    depends_on:
      - mysql
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: love-diary-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mysql_data: 